// This file is generated by Gemini.
'use server';
/**
 * @fileOverview An AI opponent level generator.
 *
 * - generateAiChessOpponent - A function that generates the AI opponent level.
 * - GenerateAiChessOpponentInput - The input type for the generateAiChessOpponent function.
 * - GenerateAiChessOpponentOutput - The return type for the generateAiChessOpponent function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateAiChessOpponentInputSchema = z.object({
  completedGames: z
    .number()
    .describe('The number of completed games for the player.'),
});
export type GenerateAiChessOpponentInput = z.infer<typeof GenerateAiChessOpponentInputSchema>;

const GenerateAiChessOpponentOutputSchema = z.object({
  opponentLevel: z
    .string()
    .describe('The difficulty level of the AI opponent (e.g., Beginner, Intermediate, Advanced).'),
});
export type GenerateAiChessOpponentOutput = z.infer<typeof GenerateAiChessOpponentOutputSchema>;

export async function generateAiChessOpponent(
  input: GenerateAiChessOpponentInput
): Promise<GenerateAiChessOpponentOutput> {
  return generateAiChessOpponentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateAiChessOpponentPrompt',
  input: {schema: GenerateAiChessOpponentInputSchema},
  output: {schema: GenerateAiChessOpponentOutputSchema},
  prompt: `You are an expert chess coach, who can evaluate the skill level of the opponent based on the player's experience.

  Based on the number of completed games the player has, suggest an appropriate AI opponent level. The number of completed games is {{{completedGames}}}.

  If the number of completed games is less than 10, the opponent level should be "Beginner". If the number of completed games is between 10 and 50, the opponent level should be "Intermediate". If the number of completed games is greater than 50, the opponent level should be "Advanced".`,
});

const generateAiChessOpponentFlow = ai.defineFlow(
  {
    name: 'generateAiChessOpponentFlow',
    inputSchema: GenerateAiChessOpponentInputSchema,
    outputSchema: GenerateAiChessOpponentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
